### ISSUE TITLE
Additional examples/resources

### ISSUE THREAD

**Issue by bvezilic** [MarquezProject/marquez-airflow-quickstart#4]
Hi!

I am familiarizing myself with how Marquez can be used with Airflow by looking at this example and I've successfully set-up everything (dockerized Airflow, Marquez, etc.) but after running the example DAGs there aren't any records of metadata in marquez-db.

Is this intentional behavior? Are there any other examples that showcase how marquez can be used with airflow to process and version datasets?

Thanks!

**Comment by wslulciuc** [comment]
Hey, @bvezilic! No, not the intended behavior at all. Thanks for letting us know. We’re currently working on addressing them. You can follow the progress here https://github.com/MarquezProject/marquez-airflow/pull/49

**Comment by bvezilic** [comment]
Great! Thanks for the quick response, I'll definitely follow the development. :)
